---
title: Verbind verbindingsdraden aan elkaar om ze te verlengen
hero_image: images/banner.png
description: Verbind verbindingsdraden aan elkaar om ze te verlengen
version: 4
listed: false
copyedit: false
last_tested: "2022-02-16"
steps:
  - title: Verbind verbindingsdraden aan elkaar om ze te verlengen
