title: Joining jumper wires
hero_image: images/banner.png
description: joining-jumper-wires description
version: 4
listed: false
copyedit: false
last_tested: "2022-02-16"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
