---
title: Joindre des fils de liaison pour les prolonger
hero_image: images/banner.png
description: Joindre des fils de liaison pour les prolonger
version: 4
listed: false
copyedit: false
last_tested: "2022-02-16"
steps:
  - title: Joindre des fils de liaison pour les prolonger
